import React from 'react';
import Head from 'next/head'
import useSWR from 'swr'
import { useRouter } from 'next/router'
import Layout from '../../components/layout'
import Spinner from '../../components/Spinner';

import { MovieDetailProps } from '../../types';
import Link from 'next/link';

const fetcher = (url: string) => fetch(url).then(res => res.json())

const MovieDetails: React.FC<MovieDetailProps> = () => {
  const router = useRouter()
  const { id } = router.query;
  const { data, error } = useSWR(`/api/movies/${id}`, fetcher);

  return (
    <div>
      <Layout>

        {error ?
          (<p className="bg-red-100 text-red-800 p-6 rounded-lg">An error has occurred.</p>) :
          !data ? (<Spinner />) : (
          <>
          <Head>
            <title>{`${data.title} | TFMDb`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
           <div className="flex items-center justify-between mb-4">
            <Link href="/"><a className="cursor-pointer hover:text-red-700 hover:underline">⭠ Back to Trending Movies</a></Link>
            <p>Fetched from <a href={`/api/movies/${data.id}`} target="_blank" className="font-mono text-red-900 underline text-lg" rel="noreferrer">{`/api/movies/${data.id}`}<svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 inline mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
              </svg></a>
            </p>
          </div>
          <h1 className="font-bold text-2xl">{data.title}</h1>
          {data.tagline ? (<h2 className="text-lg italic">{data.tagline}</h2>) : ''}
          <div className="my-4">
            {data.genres.map((g) => (<span key={g.id} className="bg-amber-200 uppercase text-sm mr-2 px-2 h-4 rounded-lg">{g.name}</span>))}
          </div>
          <div className="space-y-4">
            <p>{data.overview}</p>
            <p><a href={data.homepage} className="text-red-700 font-semibold underline">{data.homepage}</a></p>
            <p><a href={`https://www.imdb.com/title/${data.imdb_id}`} className="text-red-700 font-semibold underline">IMDb Link</a></p>
          </div>
          <p className="mt-4">Producers: {data.production_companies.map(p=> p.name).join(', ')}</p>
        </>
        )}
      </Layout>
    </div>
  )
}

export default MovieDetails;