import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tivix Fullstack Movie Database</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <p>Homepage content</p>
      </Layout>
    </div>
  )
}

export default Home
